server:
  port: 5000
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  datasource:
    url: jdbc:mysql://shelter-database.cdcoeg0wokyc.ap-northeast-2.rds.amazonaws.com:3306/shelter?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Test1234!

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: chgs9079@gmail.com
    password: dclrujvsuitxbnmt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


s3:
  bucket: shelter-project


springdoc:
 api-docs:
  path: /v3/api-docs
  #OpenAPI 명세가 노출되는 경로 설정
  #기본값은 /v3/api/docs
  #브라우저에서 확인가능하다 : http://localhost:포트/v3/api-docs
 swagger-ui:
  path: /swagger-ui.html
  #SwaggerUI 웹페이지 접속 경로 설정
  #기본값은 /swagger-ui/index.html
  #이 설정을 통해 /swagger-ui.html로 간편하게 접속 가능하다.